name: "my docker action"
description: 'Greeting and returning 42.'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer:
    description: 'always returns 42.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - $ {{ inputs.who-to-greet }}
