name: test docker action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo to use the action locally
        uses: actions/checkout@v4.2.2
      - name: Run my container
        id: action
        uses: ./
        with:
          who-to-greet: '@hsissi'
      - name: output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"
      - name: Test the container
        if: ${{ steps.action.output.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
