name: My Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: list files
        run: |
          echo "repository ${{ github.repository }} 's files:"
          tree
  job2:
    runs-on: ubuntu-latest
    needs: myjob
    steps:
      - run: echo "Job: ${{ github.job }}"
  job3:
    runs-on: ubuntu-latest
    needs: myjob
    steps:
      - run: echo "Job: ${{ github.job }}"
  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo "Job: ${{ github.job }}"
